### ISSUE TITLE
Add support for Hack

### ISSUE THREAD

**Issue by dwlnetnl** [facebook/FBMock#31]
Please add support for Hack!

**Comment by elynde** [comment]
Hey what exactly do you mean?

**Comment by dwlnetnl** [comment]
Well eval() doesn't work in Hack.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by elynde** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
