### ISSUE TITLE
PSR-0 Compatibility

### ISSUE THREAD

**Issue by rdohms** [facebook/FBMock#4]
Would be great if this would follow PSR-0 folder/namespace structure.

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-7** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by rdohms** [comment]
So the core team ignores the issue and a bot assigns it to "closed" ... sounds legit.
